config/routes.rb
Rails.application.routes.draw do
  get 'forecasts/index'

  root 'users#index'

  resources :users do
    resources :forecasts
  end

  get 'verify', to: 'users#verify', as: 'verify'
  post 'verify', to: 'users#verify'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  validates :country_code, presence: true
  validates :phone_number, :city, :state, :country, presence: true

  validates :phone_number, length: { is: 10 }, format: { with: /\A\d{10}\z/, message: "must be 10 digits" }

  # Combine country code and phone number
  def full_phone_number
    "#{country_code}#{phone_number}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user = nil
    if session[:user_id]
      begin
        @current_user ||= User.find(session[:user_id])
      rescue ActiveRecord::RecordNotFound
      end
    else
    end
  end
end

app/controllers/forecasts_controller.rb
class ForecastsController < ApplicationController
  def index
    user  = User.find(params[:user_id])
    location = user.city
    response = HTTParty.get("http://api.weatherapi.com/v1/current.json?key=#{ENV['WEATHER_FORCAST']}&q=#{location}")
    @weather_data = JSON.parse(response.body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy, :show]

  before_action :set_client, only: [:create, :verify, :update]
  before_action :current_user, only: [:verify]
  
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    
  end

  def edit
    
  end

  def create
    channel = user_params['channel']
    @user = User.new(user_params.except('channel', 'displayed_phone_number'))

    respond_to do |format|
      if @user.save
        start_verification(@user.full_phone_number, channel)
        session[:user_id] = @user.id
        format.html { redirect_to verify_url, notice: 'User was successfully created.' }
        # format.html { redirect_to users_url, notice: 'User was successfully created.' }
        format.json { render :index, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    channel = user_params['channel']
    respond_to do |format|
      if @user.update(user_params)
        @user.update(verified: false)
        start_verification(@user.full_phone_number, channel)
        session[:user_id] = @user.id
        # format.html { redirect_to users_path, notice: 'User was successfully updated.' }
        format.html { redirect_to verify_url, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def verify
    if request.post?
      is_verified = check_verification(@current_user.full_phone_number, params['verification_code'])
      if is_verified
        @current_user.verified = true
        @current_user.save
        respond_to do |format|
          format.html { redirect_to users_path, notice: 'User was successfully verified.' }
        end
      else
        respond_to do |format|
          format.html { redirect_to verify_url, notice: 'The code was invalid.' }
        end
      end
    else
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def set_client
    @client = Twilio::REST::Client.new(ENV['TWILIO_ACCOUNT_SID'], ENV['TWILIO_AUTH_TOKEN'])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :country_code, :phone_number, :location, :city, :state, :country)
  end

  def start_verification(to, channel='sms')
    channel = 'sms' unless ['sms', 'voice'].include? channel
    verification = @client.verify.services(ENV['VERIFICATION_SID'])
                                 .verifications
                                 .create(:to => to, :channel => channel)
    return verification.sid
  end

  def check_verification(phone, code)
    verification_check = @client.verify.services(ENV['VERIFICATION_SID'])
                                       .verification_checks
                                       .create(:to => phone, :code => code)
    return verification_check.status == 'approved'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/forecasts/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Weather Forecast</title>
  <%= stylesheet_link_tag 'styles' %>
</head>
<body>
  <div class="container">
    <h1>Weather Forecast</h1>

    <p><%= image_tag('weather.webp', size: '300x200') %></p>
    <p>City: <%= @weather_data['location']['name'] %></p>
    <p>Region: <%= @weather_data['location']['region'] %></p>
    <p>Local Time: <%= @weather_data['location']['localtime'] %></p>

    <p>Temperature: <%= @weather_data['current']['temp_c'] %>°C</p>
    <p>Weather Condition: <%= @weather_data['current']['condition']['text'] %></p>
    <p>Humidity: <%= @weather_data['current']['humidity'] %></p>
    <p>Cloud: <%= @weather_data['current']['cloud'] %></p>

    <%= link_to 'Back', users_path, class: 'link' %>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherForecast</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'custom_styles', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<div class="form-container">
  <%= form_with(model: user, local: true) do |form| %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
          <% user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :first_name %>
      <%= form.text_field :first_name %>
    </div>

    <div class="field">
      <%= form.label :last_name %>
      <%= form.text_field :last_name %>
    </div>

    <div class="field">
      <%= form.label :phone_number %>
      <div class="phone-input-container">
        <%= form.select :country_code, [['+1', '+1'], ['+91', '+91'], ['+44', '+44']], prompt: 'Select Country Code', id: 'user_country_code' %>
        <%#= form.text_field :phone_number, id: 'user_displayed_phone_number', placeholder: 'Enter Phone Number' %>
        <%= form.text_field :phone_number, id: 'user_phone_number', placeholder: 'Enter Phone Number' %>
      </div>
    </div>

    <div class="field">
      <%= form.label :location %>
      <%= form.text_field :location %>
    </div>

    <div class="field">
      <%= form.label :city %>
      <%= form.text_field :city %>
    </div>

    <div class="field">
      <%= form.label :state %>
      <%= form.text_field :state %>
    </div>

    <div class="field">
      <%= form.label :country %>
      <%= form.text_field :country %>
    </div>

    <div class="actions">
      <%= form.submit 'Submit' %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="page-container">
  <h1 class="page-title">Editing User</h1>

  <%= render 'form', user: @user %>

  <div class="page-links">
    <%= link_to 'Show', @user, class: 'btn btn-secondary' %>
    <%= link_to 'Back', users_path, class: 'btn btn-secondary' %>
  </div>
</div>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Users</title>
  <%= stylesheet_link_tag 'styles' %>
</head>
<body>
  <div class="container">
    <p class="notice"><%= notice %></p>

    <h1>Users</h1>

    <table border='1'>
      <thead>
        <tr>
          <th>First name</th>
          <th>Last name</th>
          <th>Phone number</th>
          <th>Location</th>
          <th>City</th>
          <th>State</th>
          <th>Country</th>
          <th>Verified</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.first_name %></td>
            <td><%= user.last_name %></td>
            <td><%= user.full_phone_number %></td>
            <td><%= user.location %></td>
            <td><%= user.city %></td>
            <td><%= user.state %></td>
            <td><%= user.country %></td>
            <td><%= user.verified %></td>
            <td><%= link_to 'Edit', edit_user_path(user) %></td>
            <td>
              <%= form_with(model: user, url: user_path(user), method: :delete, data: { confirm: 'Are you sure?' }) do |form| %>
                <%= form.submit 'Delete', data: { turbo_frame: "user_#{user.id}" } %>
              <% end %>
             </td>
            <td>
              <%= link_to 'Weather forecast', user_forecasts_path(user) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New User', new_user_path %>
  </div>
</body>
</html>

app/views/users/new.html.erb
<div class="page-container">
  <h1 class="page-title">New User</h1>

  <%= render 'form', user: @user %>

  <div class="page-links">
    <%= link_to 'Show', @user, class: 'btn btn-secondary' %>
    <%= link_to 'Back', users_path, class: 'btn btn-secondary' %>
  </div>
</div>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>User Details</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f4f4f4;
      margin: 0;
      padding: 0;
    }

    .container {
      max-width: 600px;
      margin: 20px auto;
      padding: 0 20px;
      background-color: #fff;
      border-radius: 5px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .notice {
      background-color: #f2f2f2;
      padding: 10px;
      margin-bottom: 20px;
      border-radius: 5px;
    }

    p {
      margin-bottom: 10px;
    }

    strong {
      font-weight: bold;
    }

    .link {
      display: inline-block;
      margin-top: 20px;
      color: #333;
      text-decoration: none;
      padding: 10px 20px;
      background-color: #f2f2f2;
      border-radius: 5px;
      transition: background-color 0.3s ease;
    }

    .link:hover {
      background-color: #e0e0e0;
    }
  </style>
</head>
<body>
  <div class="container">
    <p class="notice"><%= notice %></p>

    <p>
      <strong>First Name:</strong>
      <%= @user.first_name %>
    </p>

    <p>
      <strong>Last Name:</strong>
      <%= @user.last_name %>
    </p>

    <p>
      <strong>Phone Number:</strong>
      <%= @user.full_phone_number %>
    </p>

    <%= link_to 'Back', users_path, class: 'link' %>
  </div>
</body>
</html>

app/views/users/verify.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Verify</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f4f4f4;
      margin: 0;
      padding: 0;
    }

    header {
      background-color: #333;
      color: #fff;
      padding: 20px;
      text-align: center;
    }

    header h1 {
      margin: 0;
    }

    .container {
      max-width: 600px;
      margin: 20px auto;
      padding: 0 20px;
    }

    .field {
      margin-bottom: 20px;
    }

    label {
      display: block;
      font-weight: bold;
      margin-bottom: 5px;
    }

    input[type="text"] {
      width: 100%;
      padding: 10px;
      font-size: 16px;
    }

    .actions {
      text-align: center;
    }

    button {
      padding: 10px 20px;
      background-color: #333;
      color: #fff;
      border: none;
      border-radius: 5px;
      cursor: pointer;
      font-size: 16px;
    }

    button:hover {
      background-color: #555;
    }

    #notice {
      text-align: center;
      margin-bottom: 20px;
    }

    a {
      display: block;
      text-align: center;
      color: #333;
      text-decoration: none;
      margin-top: 20px;
    }
  </style>
</head>
<body>
  <header>
    <h1>Verify</h1>
  </header>

  <div class="container">
    <p id="notice"><%= notice %></p>

    <%= form_tag(verify_url) do %>
      <div class="field">
        <%= label_tag :verification_code %>
        <%= text_field_tag :verification_code %>
      </div>

      <div class="actions">
        <%= submit_tag 'Verify' %>
      </div>
    <% end %>

    <%= link_to 'Back', users_path %>
  </div>
</body>
</html>